### ISSUE TITLE
运行报错了。

### ISSUE THREAD

**Issue by Leoxululu** [SureeLee/ga_bp#1]
我运行的是main文件，好像里面那个ga_enconding函数不能用。

**Comment by hhhush** [comment]
An error occurred in both two main.py 
i gotfollowing output:
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
`Traceback (most recent call last):
  File "ga_main.py", line 27, in <module>
    obj = ga_calObject(pop)
  File "../ga_bp_real/ga_calObject.py", line 12, in ga_calObject
    temp = bp_train(xi)
  File "../ga_bp_real/bp_train.py", line 65, in bp_train
    biases_2 = tf.Variable(tf.cast(np.mat(b2), dtype=tf.float32),name='biases_2')
  File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 785, in cast
    x = ops.convert_to_tensor(x, name="x")
  File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1014, in convert_to_tensor
    as_ref=False)
  File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 532, in make_tensor_proto
    append_fn(tensor_proto, proto_values)
  File "tensorflow/python/framework/fast_tensor_util.pyx", line 18, in tensorflow.python.framework.fast_tensor_util.AppendFloat64ArrayToTensorProto
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)`

**Comment by SureeLee** [comment]
对不起，很久没上GitHub了，很抱歉。

**Comment by MarsLK** [comment]
没事，客气啦





------------------ 原始邮件 ------------------
发件人: "SureeLee"<notifications@github.com>;
发送时间: 2019年8月10日(星期六) 晚上11:27
收件人: "SureeLee/ga_bp"<ga_bp@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [SureeLee/ga_bp] 运行报错了。 (#1)




对不起，很久没上GitHub了，很抱歉。

**Comment by SureeLee** [comment]
嘿嘿，谢谢

**Comment by YunfeiCode1** [comment]
> 
> 
> An error occurred in both two main.py
> i gotfollowing output:
> ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
> `Traceback (most recent call last): File "ga_main.py", line 27, in <module> obj = ga_calObject(pop) File "../ga_bp_real/ga_calObject.py", line 12, in ga_calObject temp = bp_train(xi) File "../ga_bp_real/bp_train.py", line 65, in bp_train biases_2 = tf.Variable(tf.cast(np.mat(b2), dtype=tf.float32),name='biases_2') File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 785, in cast x = ops.convert_to_tensor(x, name="x") File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1014, in convert_to_tensor as_ref=False) File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref) File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function return constant(v, dtype=dtype, name=name) File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant value, dtype=dtype, shape=shape, verify_shape=verify_shape)) File "/home/zhuwendan/anaconda3/envs/tensorflow1.8/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 532, in make_tensor_proto append_fn(tensor_proto, proto_values) File "tensorflow/python/framework/fast_tensor_util.pyx", line 18, in tensorflow.python.framework.fast_tensor_util.AppendFloat64ArrayToTensorProto ValueError: Buffer has wrong number of dimensions (expected 1, got 2)`

你好，你解决了这个问题了吗？我用jupyter notebook运行main文件是报错：
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-e2920c465beb> in <module>()
      5 @author: ljs
      6 '''
----> 7 from ga_bp_binary.ga_encoding import ga_encoding
      8 from ga_bp_binary.ga_decoding import ga_decoding,ga_decoding_individual
      9 from ga_bp_binary.ga_calObject import ga_calObject

ImportError: No module named 'ga_bp_binary'

不知道怎么解决了。求指教。
